# tattoo_frontend/pubspec.yaml
name: tattooya
description: "frontend prototype project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # Router / State (안정 세트)
  go_router: 14.8.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  # HTTP / API
  dio: 5.9.0
  retrofit: 4.6.0
  dio_cache_interceptor: 4.0.5
  http_cache_hive_store: 5.0.1

  # Models
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # UI / Utils
  cached_network_image: 3.4.1
  responsive_framework: 1.5.1
  flutter_svg: 2.2.1
  logger: 2.6.2
  shared_preferences: 2.5.3
  sentry_flutter: 9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 생성 (이 버전이 test_api 체인과 안 싸움)
  build_runner: 2.4.15

  retrofit_generator: 9.6.0
  riverpod_generator: 2.6.4
  freezed: 2.5.8
  json_serializable: 6.9.5
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  generate: true
