name: core_interfaces
description: Abstract ports for repositories/services
publish_to: "none"
version: 0.1.0
environment: { sdk: ">=3.9.0 <4.0.0" }
dependencies:
  core_domain:
    path: ../core_domain
dev_dependencies:
  test: ^1.25.2