# tattoo_frontend/apps/app_web/pubspec.yaml
name: app_web
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  go_router: 14.8.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  dio: 5.9.0
  retrofit: 4.6.0
  cached_network_image: 3.4.1
  responsive_framework: 1.5.1
  flutter_svg: 2.2.1
  logger: 2.6.2
  shared_preferences: 2.5.3
  sentry_flutter: 9.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.15
  riverpod_generator: 2.6.4
  retrofit_generator: 9.6.0
  freezed: 2.5.8
  json_serializable: 6.9.5
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  generate: true
